infinispan/infinispan-management-console

src/main/webapp/cache-details/cache-details.html, src/main/webapp/cluster-view/cluster-view.html, src/main/webapp/clusters-view/clusters-view.controller.js, src/main/webapp/components/api/cache-creation-controller.service.js, src/main/webapp/components/api/cache-model.service.js, src/main/webapp/components/api/cluster-model.service.js, src/main/webapp/components/directives/cache/distributed-cache.html, src/main/webapp/components/directives/cache/general/general.html, src/main/webapp/components/directives/cache/general/general.js, src/main/webapp/components/directives/cache/general/generaldist.html, src/main/webapp/components/directives/cache/general/generaldist.js, src/main/webapp/components/directives/cache/general/generalinvalidation.html, src/main/webapp/components/directives/cache/general/generalinvalidation.js, src/main/webapp/components/directives/cache/general/generallocal.html, src/main/webapp/components/directives/cache/general/generallocal.js, src/main/webapp/components/directives/cache/general/generalreplicated.html, src/main/webapp/components/directives/cache/general/generalreplicated.js, src/main/webapp/components/directives/cache/invalidation-cache.html, src/main/webapp/components/directives/cache/local-cache.html, src/main/webapp/components/directives/cache/replicated-cache.html, src/main/webapp/components/navbar/navbar.controller.js, src/main/webapp/components/services/utils.js, src/main/webapp/create-cache/create-cache.controller.js, src/main/webapp/create-cache/create-cache.html
First pass to enable cache creation from templates. Next step is to create cache templates from UI.
=> Enable cache creation from templates

bower.json, src/main/webapp/cluster-nodes/cluster-nodes.html
Upgrade to the latest PF 2.4.0 release. Minor fix that did not get merged in the latest PR as well. @tristantarrant please review and integrate
=> Upgrade to Patternfly 2.4.0

src/main/webapp/cache-status/cache-status.controller.js, src/main/webapp/cache-status/cache-status.html, src/main/webapp/cluster-nodes/cluster-nodes.controller.js, src/main/webapp/cluster-nodes/cluster-nodes.html, src/main/webapp/components/api/server-model.service.js, src/main/webapp/node-status/confirmation-node-modal.html, src/main/webapp/node-status/node-status.controller.js, src/main/webapp/node-status/node-status.html
Contains suggestions/fixes from Berlin review with Pedro (except configuration fixes). Please have a look @tristantarrant
=> Berlin review 

src/main/webapp/cache-nodes/cache-nodes.html, src/main/webapp/cache-status/cache-status.controller.js, src/main/webapp/cache-status/cache-status.html, src/main/webapp/cluster-nodes/cluster-nodes.controller.js, src/main/webapp/cluster-view/cluster-view.controller.js, src/main/webapp/cluster-view/cluster-view.html, src/main/webapp/clusters-view/clusters-view.controller.js, src/main/webapp/components/api/cache-creation-controller.service.js, src/main/webapp/components/api/cache-model.service.js, src/main/webapp/components/api/cluster-model.service.js, src/main/webapp/components/api/domain-model.service.js, src/main/webapp/components/api/node-creation-controller.service.js, src/main/webapp/components/api/server-model.service.js, src/main/webapp/components/api/servergroup-model.service.js, src/main/webapp/components/directives/cache/configurationSection.js, src/main/webapp/components/directives/cache/configurationViewer.js, src/main/webapp/components/directives/cache/jdbcstore/jdbcstore.js, src/main/webapp/components/directives/finishRender/finishRender.js, src/main/webapp/components/directives/match-height/match-height.js, src/main/webapp/components/services/utils.js, src/main/webapp/edit-cache/edit-cache.controller.js, src/main/webapp/login/login.controller.js, src/main/webapp/management-console.js, src/main/webapp/node-status/node-status.controller.js, src/main/webapp/node-status/node-status.html
Master only. Linting errors have been minimized. Includes fixes for ISPN-5915 ISPN-5920 ISPN-5970 and ISPN-5996
=> Cumulative fixes 

src/main/webapp/cache-nodes/cache-nodes.html, src/main/webapp/cache-status/cache-status.html, src/main/webapp/cache-status/confirmation-cache-modal.html, src/main/webapp/cluster-nodes/add-node-modal.html, src/main/webapp/cluster-nodes/cluster-nodes.html, src/main/webapp/cluster-view/add-cache-modal.html, src/main/webapp/cluster-view/cluster-view.html, src/main/webapp/clusters-view-physical/clusters-view.html, src/main/webapp/clusters-view/clusters-view.html, src/main/webapp/components/api/cache-model.service.js, src/main/webapp/components/directives/cache/configuration-section.html, src/main/webapp/edit-cache/confirmation-cache-modal.html, src/main/webapp/edit-cache/edit-cache.html, src/main/webapp/node-status/confirmation-node-modal.html, src/main/webapp/node-status/node-status.html
Master only. @Holmistr needs to review before we integrate!
=> ISPN-5941 Ensure testability of management console

src/main/webapp/cache-container/cache-container-configuration-service.js, src/main/webapp/cache-container/configuration-deploy/deploy.html, src/main/webapp/cache-container/configuration-deploy/edit-deploy.controller.js, src/main/webapp/cache-container/configuration-deploy/upload-artifact-modal.html, src/main/webapp/cache-container/configuration-security/edit-security.controller.js, src/main/webapp/cache-container/configuration-security/security.html, src/main/webapp/components/api/cluster-model.service.js, src/main/webapp/components/api/model-controller.service.js, src/main/webapp/management-console.js
Master only. @tristantarrant @pzapataf I got upload and remove to work for deployments but I could not get DMR op for deploy and undeploy correctly. The ones you found Tristan do not work, so I attempted variations, different endpoints to no luck. I downloaded Wildfly and tried to decode their dmr ops for deploy and undeploy - they seem not to use management-upload but rather management endpoint directly. However, they seem to use composite ops for deploy and undeploy. I need a bit more time to figure these out. I think it is ok if we release beta2 with this PR included. At least, deployments can be uploaded/removed - we'll get the rest done soon! Please try it out on a fresh server build without proxy before integrating. Thank you!
=> ISPN-5813 Initialize security and basic upload/remove

src/main/webapp/cache-container/cache-container-configuration-service.js, src/main/webapp/cache-container/configuration-deploy/confirmation-deploy-modal.html, src/main/webapp/cache-container/configuration-deploy/deploy.html, src/main/webapp/cache-container/configuration-deploy/edit-deploy.controller.js, src/main/webapp/cache-container/configuration-deploy/upload-artifact-modal.html, src/main/webapp/components/api/model-controller.service.js, src/main/webapp/management-console.js
Master only. Fully functional deploy/undeploy and content remove. Along with modal confirmation dialogs.
=> ISPN-5813 - View of cache container configuration (deploy/undeploy)

src/main/webapp/cache-container/configuration-security/edit-security.controller.js, src/main/webapp/cache-container/configuration-security/security.html, src/main/webapp/cache-status/cache-status.controller.js, src/main/webapp/cluster-nodes/cluster-nodes-service.js, src/main/webapp/cluster-nodes/cluster-nodes.controller.js, src/main/webapp/cluster-view/cluster-view.controller.js, src/main/webapp/cluster-view/cluster-view.html, src/main/webapp/components/api/cluster-model.service.js, src/main/webapp/components/api/server-model.service.js, src/main/webapp/components/api/servergroup-model.service.js, src/main/webapp/components/dialogs/generic-info.html, src/main/webapp/components/dialogs/generic-ok-cancel.html, src/main/webapp/management-console.js, src/main/webapp/node-status/confirmation-node-modal.html, src/main/webapp/node-status/node-status.controller.js, src/main/webapp/node-status/node-status.html
Master only. Cumulative fixes - getting console ready for 8.2 release
=> Cumulative fixes. See commits for details

src/main/webapp/cache-status/cache-service.js, src/main/webapp/cache-status/cache-status.controller.js, src/main/webapp/cache-status/cache-status.html, src/main/webapp/cache-status/confirmation-cache-modal.html, src/main/webapp/components/api/cache-model.service.js, src/main/webapp/index.html
Master only. Eviscerate cache ops from cache model and move them to service + add reindex op only for indexable caches
=> ISPN-6339 Add mass reindex operation

src/main/webapp/cluster-nodes/cluster-nodes-service.js, src/main/webapp/clusters-view/clusters-view.controller.js, src/main/webapp/components/api/cluster-model.service.js, src/main/webapp/components/api/profile-model.service.js, src/main/webapp/management-console.js
Master only. However, please DO NOT integrate yet @tristantarrant This is just a proof that we can adapt a model to have complex domain setups work. However, I need a few more days to make sure everything works as expected.
=> ISPN-6378 Console doesn't scope cache containers to server-groups

src/module/cache-container/CacheContainer.ts, src/module/cache-container/CacheContainerCtrl.ts
TypeScriptFresh only. Please integrate @ryanemerson
=> Remove rebalancing flicker on cache container page

src/module/server-group/ServerGroup.ts, src/module/server-group/ServerGroupCtrl.ts
TypeScriptFresh only. Please integrate @ryanemerson
=> Remove STARTED/DEGRADED flicker on cluster page

src/module/cache-container/view/cache-container.html, src/module/cache/view/cache.html, src/module/cache/view/nodes.html, src/module/navbar/view/navbar.html, src/module/server-group/view/server-group.html, src/module/server-instance/view/server-instance.html
TypeScriptFresh only. Please integrate @ryanemerson
=> Avoid double click dropdown invocation

src/ManagementConsole.ts, src/components/directives/VertilizeContainerDirective.ts, src/components/directives/VertilizeDirective.ts, src/jspm.conf.js, src/module/cache-container/caches/view/caches.html, src/module/cache/view/cache.html, src/module/server-group/view/server-group.html, src/module/server-instance/view/server-instance.html
TypescriptFresh only. @ryanemerson please review and integrate
=> Rewrite Vertilize in Typescript and match height on card divs

src/module/server-instance/view/server-instance.html
Trivial fix @ryanemerson . Please verify and integrate!
=> Fix clusters link on server instance page

src/components/cache-loaders/CacheLoadersCtrl.ts, src/components/cache-loaders/view/cache-loaders.html
Master only. Please review @ryanemerson
=> Remove YO from loaders panel

src/module/cache-container/SiteManagementModalCtrl.ts, src/module/cache-container/caches/view/caches.html, src/module/cache-containers/CacheContainersCtrl.ts, src/module/cache-containers/view/cache-containers.html, src/services/container/ICacheContainer.ts
Master only. Apparently, the ra data from DMR has these sites online|offline|mixed reversed. Please review and integrate @ryanemerson
=> ISPN-7201 Administration console - remote sites are not displayed

src/module/server-group/ServerGroupCtrl.ts, src/module/server-instance/view/server-instance.html
Master only. Please verify and integrate @ryanemerson
=> ISPN-7204 Administration console - cluster page doesn't show correct node status

src/main/webapp/components/api/cluster-model.service.js
https://issues.jboss.org/browse/ISPN-6931
=> [8.2.x] ISPN-6931: Cache container screen not shown if connector removed.

src/module/cache-container/tasks/TasksCtrl.ts, src/module/cache-container/tasks/view/tasks-history.html
Master only. Do not integrate yet. @ryanemerson can you attempt to shrink select widget *not* to take entire page width? Give it a try before I call some more specialized CSS help
=> ISPN-7206 Administration console - task history only shows last 10 tasks

src/services/cache/Cache.ts
Master only. Trivial. Please verify and integrate @ryanemerson See https://issues.jboss.org/browse/ISPN-7217 for more details
=> ISPN-7217 Transactional filter doesn't work on NON_XA cache

src/module/cache/view/cache.html, src/module/cache/view/nodes.html
Master only. Trivial. Please integrate @ryanemerson See https://issues.jboss.org/browse/ISPN-7216
=> ISPN-7216 General status link doesn't work correctly

src/module/cache-container/config/thread-pools/ThreadPoolsCtrl.ts, src/module/cache-container/config/transport/TransportConfigCtrl.ts, src/module/cache-templates/CacheTemplatesCtrl.ts, src/module/cache/config/CacheConfigCtrl.ts, src/services/domain/DomainService.ts, src/services/server-group/ServerGroupService.ts
Master only. See https://issues.jboss.org/browse/ISPN-7214 for more details. We need it for JDG-447
=> ISPN-7214 Scope server restarts to server group

src/module/cache-container/tasks/view/tasks.html
Master only. Trivial state reload on ui-sref transitions.
=> Completed tasks are not shown in task history right away

src/module/server-instance/ServerInstanceCtrl.ts, src/module/server-instance/view/server-instance.html
Master only. Trivial, but please verify anyways. See https://issues.jboss.org/browse/ISPN-7248 for more details
=> ISPN-7248 Start/stop/remove node actions should not be available in standalone mode

src/module/cache-container/config/thread-pools/ThreadPoolsCtrl.ts, src/module/cache-container/config/transport/TransportConfigCtrl.ts, src/module/cache-templates/CacheTemplatesCtrl.ts, src/module/cache/config/CacheConfigCtrl.ts
Master only. See https://issues.jboss.org/browse/ISPN-7251 for more details
=> ISPN-7251 Changing configuration in standalone mode should not prompt restart dialog

src/module/cache-container/config/ContainerConfig.ts
Master only. Workaround until we solve the mystery of BULK_READ permission for get-proto-schema-names DMR call
=> ISPN-7264 BULK_READ permission is not set in identity/role (workaround)

src/services/cache/CacheService.ts
Master only. See https://issues.jboss.org/browse/ISPN-7293 for more details.
=> ISPN-7293 Status of invalidation caches is not displayed correctly

src/module/cache-container/caches/AddCacheModalCtrl.ts, src/module/cache/Cache.ts, src/module/cache/config/CacheConfigCtrl.ts
Master only. See https://issues.jboss.org/browse/ISPN-7294 for more details
=> ISPN-7294 Creating new cache from template should prompt confirmation

src/components/cache-security/CacheSecurityCtrl.ts, src/components/configuration-section/ConfigurationSectionCtrl.ts, src/services/cache-config/CacheConfigService.ts
Master only. Do not blindly integrate. This is a working proposal to be considered
=> ISPN-7247 changing any cache configuration adds security tag to the configuration (addendum)

src/module/cache-container/config/deployments/view/deploy.html
Master only. Resolves https://issues.jboss.org/browse/ISPN-7331 in an even better and simpler way than suggested. We enable/disable remove button in appropriate states. Please review @ryanemerson
=> ISPN-7331 Removing task before undeploying it should show an error

src/module/server-groups/ServerGroupsCtrl.ts, src/module/server-groups/view/server-groups.html
Master only. Please review and integrate @ryanemerson
=> ISPN-7336 There is a reference to domain in standalone mode

src/module/server-group/ConfirmationModalCtrl.ts, src/module/server-group/ServerGroupCtrl.ts, src/module/server-group/view/confirmation-modal.html
Master only. Please verify and integrate @ryanemerson
=> ISPN-7345 Missing name of cluster in stop/start confirmation dialog

src/module/cache-container/config/tasks/view/edit-script-modal.html
Trivial but verify please @ryanemerson I tried Chrome and Firefox
=> ISPN-7353 Additional information in new script dialog is not displayed

src/services/schemas/SchemasService.ts
Master only. Patch for reopened ISPN-7228. Please review @ryanemerson
=> ISPN-7228 Creating wrong schema doesn't show error message (addendum)

src/components/cache-stores/view/modal-template.html
https://issues.jboss.org/browse/ISPN-7469
=> ISPN-7469 JDBC store elements have the same IDs.

src/module/server-group/view/booting-modal.html, src/module/server-group/view/stopping-modal.html
Master only. Please review @ryanemerson
=> ISPN-7628 The cluster status doesn't reflect reload-required state of its nodes (addendum)

src/module/server-instance/ServerInstanceCtrl.ts
Master only. Please see https://issues.jboss.org/browse/ISPN-7698 for details. Review the proposed fix and integrate.
=> ISPN-7698 Minor issues with removing node

src/module/server-group/view/server-group.html
Master only. See https://issues.jboss.org/browse/ISPN-7705 for more details.
=> ISPN-7705 Greyed out cluster action can still be selected

src/module/cache-container/tasks/view/tasks-create.html
Master only. See https://issues.jboss.org/browse/ISPN-7726 for details. Please have a look @ryanemerson
=> ISPN-7726 Task execution failure does not display the cause of failure

src/module/cache/view/nodes.html
Master and 9.0.x preview only. See https://issues.jboss.org/browse/ISPN-7733 for more details.
=> ISPN-7733 Incorrect data field columns used on cache nodes page

src/module/cache/CacheCtrl.ts
Master and 9.0.x See more details at https://issues.jboss.org/browse/ISPN-7746
=> ISPN-7746 Reset statistics action is not wired on General Status cache page

src/module/cache-containers/view/cache-containers.html
Master only. Removes burger action menu in standalone mode (cache containers page)
=> ISPN-8039 Remove action menu for cache container in standalone mode

src/module/cache-container/config/ContainerConfig.ts, src/module/cache-container/config/transport/view/transport-meta.json, src/services/metadata/MetadataService.ts
@ryanemerson I enhanced dynamic reflection so it includes params in IStateParamsService. Please see if it makes sense to you and check out the example I did for channel name reflection in container transport tab. If all good, please see if you can add cache loaders/stores as your commits on top of this branch. If you are not able to achieve that task then we can further enhance dynamic reflection/invocation. LMK
=> ISPN-7915 

src/services/cache-config/CacheConfigService.ts
Master only. See https://issues.jboss.org/browse/ISPN-7649
=> ISPN-7649 Administration console - transaction tab allows to set invalid options

src/module/server-instance/view/server-instance.html
=> ISPN-8292 Server instance mappedBufferPoolCount not displayed (addendum)

src/module/server-instance/ServerInstanceCtrl.ts, src/module/server-instance/view/server-instance.html
Master only. Needed for product side but it makes sense to include this logic upstream as well. Please review @ryanemerson
=> ISPN-8351 Administration console - allow restart/reload of a running server

assets/languages/locale-enUS.txt, src/index.ts, src/module/cache-container/CacheContainer.ts, src/module/cache-container/counters/CounterCreateModalCtrl.ts, src/module/cache-container/counters/CountersCtrl.ts, src/module/cache-container/counters/view/counters-create.html, src/module/cache-container/counters/view/counters.html, src/module/cache-container/view/cache-container.html, src/services/counters/AbstractCounter.ts, src/services/counters/CounterService.ts, src/services/counters/ICounter.ts, src/services/counters/StrongCounter.ts, src/services/counters/WeakCounter.ts
Master only as it requires 9.2 counters DMR. PR for counters is at https://github.com/infinispan/infinispan/pull/5570 and as soon as it gets integrated we can try out this PR and integrate it as well. In the meantime, let's look at things that need to be ironed out so this PR is ready to go as well.
=> ISPN-7927 User Interface to manage Cluster Counters

src/module/cache-container/config/schemas/SchemaModalCtrl.ts
@ryanemerson I simplied the workflow and error feedback to adhere the already established Patternfly paradigms. We should in fact go once again through all modal dialogs and update any inconsistencies like this one.
=> ISPN-8642 Administration console - updating scheme doesn't close the update dialog

src/common/utils/Utils.ts, src/module/cache/CacheCtrl.ts, src/module/cache/view/cache.html
Master only. Similar to how we converted bytes to appropriate sizes lets also convert avg read/write stats
=> ISPN-8434 Management console should write/read time unit and adjust it

src/module/server-group/view/server-group.html
Master only. @ryanemerson after reviewing the latest comments from Roman I think we should do this to complete https://issues.jboss.org/browse/ISPN-7705 Please see if that makes sense to you as well and if it does - integrate.
=> ISPN-7705 Administration console - greyed out cluster action can still be selected (final)

src/services/counters/CounterService.ts
Master only. See https://issues.jboss.org/browse/ISPN-8797 for more details
=> ISPN-8797 Administration console - Counters tab - reset counter does not work

src/common/utils/Utils.ts, src/module/cache-container/config/schemas/SchemaModalCtrl.ts, src/module/cache-container/counters/view/counters-create.html
Master only. See https://issues.jboss.org/browse/ISPN-8795
=> ISPN-8795 Administration console - Create new counter dialog

src/common/utils/Utils.ts
Master only. Please see https://issues.jboss.org/browse/ISPN-8842 for more details.
=> ISPN-8842 Administration console shows only blank page on IE

src/common/utils/Utils.ts, src/services/dmr/DmrService.ts
Master only. Please review @ryanemerson
=> ISPN-8460 Administration console - create user friendly configuration validation errors

src/ManagementConsole.less
@ryanemerson please run it yourself to verify all good to go.
=> ISPN-8759 Add data manipulation capabilities (codemirror css fix)

src/services/cache/CacheService.ts, src/services/server/ServerService.ts
Master only. Please review @ryanemerson
=> ISPN-9056 Cache metrics per node not displayed when one of nodes is stopped

src/services/server/ServerService.ts
Master only. Mark new nodes to have auto-start true
=> ISPN-9058 Auto-start feature/flag for nodes added from Management Console

src/module/server-group/ServerGroup.ts, src/module/server-group/ServerGroupCtrl.ts, src/services/domain/DomainService.ts
=> ISPN-9066 Successfully configured Slave node with no server configured is not shown in the list of hosts

package.json, pom.xml
=> Bump version to 9.3.0-SNAPSHOT

src/module/cache-container/view/cache-container.html, src/services/counters/CounterService.ts
@ryanemerson we can merge this one into 9.2 and master, of course.
=> ISPN-8989 Administration console - Counters don't work in standalone mode

src/ManagementConsole.ts
Trivial. Adding JSON syntax highlighting
=> ISPN-8759 Add JSON syntax highlighting

src/module/cache-container/config/tasks/ScriptModalCtrl.ts, src/module/cache-container/config/tasks/view/edit-script-modal.html
Master branch only. See https://issues.jboss.org/browse/ISPN-7085 for more details @ryanemerson make sure that on your ISPN branch https://github.com/infinispan/infinispan/pull/6000 is integrated
=> ISPN-7085 Add Codemirror editor for editing scripts

src/module/server-instance/ServerInstance.ts, src/module/server-instance/ServerInstanceCtrl.ts
=> ISPN-9331 Cluster node page flickers angular ctrl variables

tasks/server.js
Master only. Please verify @ryanemerson
=> Update proxy settings for WildFly 13

tasks/constants.js
=> If branding not configured use default - Infinispan

src/services/jgroups/JGroupsService.ts
See more details at https://issues.jboss.org/browse/ISPN-9462
=> ISPN-9642 Management console displays nothing after enabling server hinting

src/common/configuration/ConfigUtil.ts
https://issues.jboss.org/browse/ISPN-9763
This requires https://github.com/infinispan/infinispan/pull/6515
=> [9.4.x] ISPN-9763 Model descriptions updated to include persistence element

src/services/cache-config/CacheConfigService.ts, src/services/dmr/IDmrRequest.ts
Co-authored-by: Ryan Emerson <remerson@redhat.com>
https://issues.jboss.org/browse/ISPN-9952
=> ISPN-9952 Admin console hangs after cache create
